### ISSUE TITLE
As a non-technical legal aid intern, I need to convert the elements of a PDF to a web form so that I can capture information submitted from members of the public.

### ISSUE THREAD

**Issue by emilylordahl** [GSA-TTS/atj-platform#115]
Based on the existing components created in [#79](https://github.com/GSA-TTS/atj-platform/issues/79), create a user experience that enables content authors to convert their PDF manually from scratch, focusing on the Kansas name change form and its content.

Example considerations:

CRUD for pages, questions, sections with or without questions, etc.
Drag and drop to rearrange question order
Consider clarity, accessibility and usability best practices
Small and medium device sizes are supported but the UX should be optimized for larger screens as the legal aids will be working on this task in an office environment.

Acceptance criteria
- [x] Annotated mock-ups, as appropriate, demonstrate CRUD for pages, stand alone questions and sections that contain questions
- [x] Menus for page, section and question creation menus are ready for engineering (includes all elements and relevant state changes, not necessarily pixel-perfect)
```[tasklist]
### Tasks
- [x] Revisit [UX teardown](https://github.com/GSA-TTS/atj-platform/issues/60) recommendations with new understanding
- [x] Document and share potential workflow(s) to uncover questions
- [x] Create and share small screen designs and components
- [x] Modify small screen designs and components for med and large screen sizes
- [x] Design review of Test View UI
- [x] Review the actual implementation of the designs for the Test View UI
```

**Comment by espythomson** [comment]
@emilylordahl ready for mobile review

**Comment by emilylordahl** [comment]
Looks great, @espythomson! I added comments throughout and tagged you. Let me know if you need any clarification or support!

**Comment by emilylordahl** [comment]
Please note that we've migrated to a new GSA Figma space. Design work is now tracked in Figma [here](https://www.figma.com/file/RAm1GWbVTdBpzlmaLL6pLO/ATJ-Platform?type=design&node-id=574%3A170&mode=design&t=QCuKM2vtr0mxZT7e-1).
