### ISSUE TITLE
Gather feedback from content authors

### ISSUE THREAD

**Issue by emilylordahl** [GSA-TTS/atj-platform#116]
Create a research study test plan to capture feedback from content authors, focused on the build of the Kansas name change form.

Items and goals to consider:
- What are the riskiest assumptions we have that we want to observe and validate in testing?
- For a simple form, what is the absolutely bare minimum editing interface?
- For patterns like name that are not required by default, observe if the user is able to complete the task of accurately creating their form. (error recovery)
- Are people able to make the right question type choices based on the descriptions we’ve provided? (clarity)
- Are people trying to use the back or delete key to undo or exit when editing a question? (usability)

Acceptance criteria
- [x] Draft plan is peer reviewed by @espythomson and shared with Kansas Emily
- [x] The study purpose, expectations, test logistics and script are defined and shared on this ticket
```[tasklist]
### Tasks
- [x] Decide on methodology (usability testing, interview + product walkthrough, something else?)
- [ ] If usability testing, fill in [testing framework](https://www.usertesting.com/blog/remote-usability-test-framework)
- [x] Decide on methods of consent, compensation, PRA concerns, etc.
- [ ] Create tickets to conduct test and synthesize test results
- [x] Brainstorming around options for showing form builder users the data that is being requested and saved
```

**Comment by emilylordahl** [comment]
Comments from KS Emily:

- Capturing the name change people might be harder to capture. The clerk usually handles this one because it's simple. These users are not usually in need of as much help or guidance.
  - People getting married
  - Trans people
  - Example: Men named Leslie 
- She’s been brainstorming about ways to access other people (libraries, late night places) with her mentor.  She wants to find people who are not comfortable with the legal system. This is something to consider for target audience recruitment limitations.

**Comment by espythomson** [comment]
@emilylordahl I reviewed the words and added suggestions of which ones to cut, with reasoning, on slide 3. Depending how many you think would be good to cut, there are extra ones that could be cut at the bottom of the notes on slide 3. I think a variety of words is nice though!
https://docs.google.com/presentation/d/1YyB0d0NEhssYUnZIzGYiCN8P-EVo7U3hgCP0hT286KE/edit#slide=id.g2bf61c7a9fb_0_391
