### ISSUE TITLE
"My Forms" page

### ISSUE THREAD

**Issue by danielnaab** [GSA-TTS/atj-platform#131]
Implement the "My Forms" page, consistent with the Figma mocks.

Context: There are currently two form lists - the "available forms" list, which provides links to the publicly-accessible versions of the forms, and the "Manage Forms" page, which provides content creators access to CRUD operations. This work would involve retiring the former, and merging its functions into the latter.

- [Mobile](https://www.figma.com/design/RAm1GWbVTdBpzlmaLL6pLO/ATJ-Platform?node-id=87-26605&t=Psr7lyusg1PkhBhh-0)
- [Desktop](https://www.figma.com/design/RAm1GWbVTdBpzlmaLL6pLO/ATJ-Platform?node-id=1367-18082&t=btPtIJYOylmXYxsA-0)

Acceptance criteria:

- [x] Implementation matches Figma mocks
- [x] All frontend behavior has test coverage
- [x] Ensure implementation of pdf upload success & fail toasts

```[tasklist]
### Tasks
```

**Comment by ethangardner** [comment]
Completed in https://github.com/GSA-TTS/atj-platform/pull/143. Will open other ticket to address issues in PR comments.
