### ISSUE TITLE
Create showcase form - Alabama name change form

### ISSUE THREAD

**Issue by danielnaab** [GSA-TTS/atj-platform#21]
As a self-represented litigant / research subject, I would like to file for a name change in the state of Alabama.

Acceptance criteria:

- A no code interface exists to define a guided interview capable of completing the fillable PDF version of the Alabama name change form
- An accessible web form with appropriate layout is generated from the guided interview definition
- On submission, the end-user may download a completed Alabama name change form

These conditions apply:

- No custom logic is required for this form. Each field in the web form will map 1-to-1 to a PDF field.
- The entire web form should be presented on a single page.

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/atj-platform/issues/36
- [x] Add actions (buttons) to the prompt definition
- [ ] https://github.com/GSA-TTS/atj-platform/issues/43
- [ ] https://github.com/GSA-TTS/atj-platform/issues/41
- [ ] https://github.com/GSA-TTS/atj-platform/issues/38
- [ ] https://github.com/GSA-TTS/atj-platform/issues/71
- [ ] https://github.com/GSA-TTS/atj-platform/issues/35
- [ ] https://github.com/GSA-TTS/atj-platform/issues/22
- [ ] https://github.com/GSA-TTS/atj-platform/issues/23
- [ ] (Stretch - could be stand-alone user story) https://github.com/GSA-TTS/atj-platform/issues/24
- [ ] https://github.com/GSA-TTS/atj-platform/issues/45
- [ ] https://github.com/GSA-TTS/atj-platform/issues/46
```
