### ISSUE TITLE
Feature: share forms with teammates

### ISSUE THREAD

**Issue by danielnaab** [GSA-TTS/atj-platform#247]
## Overview

As a user, I would like save my forms, so I can collaborate with teammates on forms I've created.

## Context

This involves creating a persistence layer and implementing auth. An MVP is the happy path.

## Tasks

- [x] Authentication
- [x] Backend storage
- [x] DB integration for forms service
- [x] Devops/deployment
- [x] UI updates?
- [x] Documentation updates

## Acceptance Criteria

- [ ] Allowlisted user may use login.gov to log in
- [ ] User-created blueprints are persisted
- [ ] Allowlisted users may view and edit all persisted forms on their organization's server

## Definition of done

The "definition of done" ensures our quality standards are met with each bit of user-facing behavior we add. Everything that can be done incrementally should be done incrementally, while the context and details are fresh. If it’s inefficient or “hard” to do so, the team should figure out why and add OPEX/DEVEX backlog items to make it easier and more efficient.

- [ ] Behavior
  - [ ] Acceptance criteria met
  - [ ] Implementation matches design decisions
- [ ] Documentation
  - [ ] ADRs (`/documents/adr` folder)
  - [ ] Relevant `README.md`(s)
- [x] Code quality
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies; dependency rule followed
  - [ ] Code is reviewed by team member
  - [x] Code quality checks passed
- [ ] Security and privacy
  - [ ] Security and privacy gates passed
- [x] Testing tasks completed
  - [x] Automated tests pass
  - [ ] Unit test coverage of our code >= 90%
- [x] Build and deploy
  - [x] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted. Document the feature toggle
  - [ ] Source code is merged to the main branch
