### ISSUE TITLE
[SSN Component] As a form-builder user, I want to ask my users to provide SSN because my form requires it. I want to make sure that users enter a valid SSN. If the pre-built web form already asks for SSN, I expect it to validate correctly.

### ISSUE THREAD

**Issue by jimmoffet** [GSA-TTS/atj-platform#278]
## Overview

As a form-builder user, I want to ask my users to provide SSN because my form requires it. I want to make sure that users enter a valid SSN. If the pre-built web form already asks for SSN, I expect it to validate correctly.

## Context

The second part above depends on the ingestion API being able to recognize and assign this component.

- [ ]

## Acceptance Criteria

*Required outcomes of the story*

- [ ] In ingestion, SSN questions are detected and correctly assigned with high enough probability to satisfy form-builder users
- [ ] If not required and validation fails, craft error message appropriately so that form-filler user understands what is happening (i.e. it's not valid, but also not necessary)
- [ ] Create ticket for converting existing questions to other question types without losing mapping (where feasible)

## Research Questions

- *Optional: Any initial questions for research*

## Tasks

*Research, design, and engineering work needed to complete the story.*

- [ ] Engineering: implement as defined: https://designsystem.digital.gov/patterns/create-a-user-profile/social-security-number/

## Definition of done

The "definition of done" ensures our quality standards are met with each bit of user-facing behavior we add. Everything that can be done incrementally should be done incrementally, while the context and details are fresh. If it’s inefficient or “hard” to do so, the team should figure out why and add OPEX/DEVEX backlog items to make it easier and more efficient.

- [ ] Behavior
  - [ ] Acceptance criteria met
  - [ ] Implementation matches design decisions
- [ ] Documentation
  - [ ] ADRs (`/documents/adr` folder)
  - [ ] Relevant `README.md`(s)
- [ ] Code quality
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies; dependency rule followed
  - [ ] Code is reviewed by team member
  - [ ] Code quality checks passed
- [ ] Security and privacy
  - [ ] Automated security and privacy gates passed
- [ ] Testing tasks completed
  - [ ] Automated tests pass
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build and deploy
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted. Document the feature toggle
  - [ ] Source code is merged to the main branch

## Decisions

- *Optional: Any decisions we've made while working on this story*

**Comment by JennyRichards-Flexion** [comment]
Archive as duplicate.
