### ISSUE TITLE
Long-press to drag questions and pages

### ISSUE THREAD

**Issue by jimmoffet** [GSA-TTS/atj-platform#284]
## Overview

As a user I want to drag questions and pages even if I don't know what the handle is or does

## Context

*Optional: Any reference material or thoughts we may need for later reference, or assumptions of prior or future work that's out of scope for this story.*

- [ ]

## Acceptance Criteria

*Required outcomes of the story*

- [ ] Long-pressing on questions (in both edit and non-edit mode) triggers drag functionality
- [ ] When dragging is triggered it should be clear to user that this is happening (we currently use purple outline, which is probably fine for now)
- [ ] Dragging surface should include entire page label div and for questions, the entire non-edit component, as well as anything that won't directly interfere with editing on the edit component (since it's a long press, we might be able to use the entire edit component div without interfering with short presses)

## Research Questions

- *Optional: Any initial questions for research*

## Tasks

*Research, design, and engineering work needed to complete the story.*

- [ ]

## Definition of done

The "definition of done" ensures our quality standards are met with each bit of user-facing behavior we add. Everything that can be done incrementally should be done incrementally, while the context and details are fresh. If it’s inefficient or “hard” to do so, the team should figure out why and add OPEX/DEVEX backlog items to make it easier and more efficient.

- [ ] Behavior
  - [ ] Acceptance criteria met
  - [ ] Implementation matches design decisions
- [ ] Documentation
  - [ ] ADRs (`/documents/adr` folder)
  - [ ] Relevant `README.md`(s)
- [ ] Code quality
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies; dependency rule followed
  - [ ] Code is reviewed by team member
  - [ ] Code quality checks passed
- [ ] Security and privacy
  - [ ] Automated security and privacy gates passed
- [ ] Testing tasks completed
  - [ ] Automated tests pass
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build and deploy
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted. Document the feature toggle
  - [ ] Source code is merged to the main branch

## Decisions

- *Optional: Any decisions we've made while working on this story*
