### ISSUE TITLE
[Design] Flesh-out a specific user story for Logic UI

### ISSUE THREAD

**Issue by jimmoffet** [GSA-TTS/atj-platform#288]
## Overview

As a Pardon staff form-builder user, I want to be able to create an eligibility page for the presidential pardon, so that my applicants can quickly and easily understand if they are eligible, ineligible or conditionally-eligible for a presidential pardon.

**NOTE:** for the purposes of simplifying this ticket, let's assume that the waiver and ineligibility screens are ready to go. We can tackle them independently alongside the Pardon team.

The UI to be designed must afford everything necessary to accomplish the scenario below:

The eligibility page must present the applicant with 4 checkboxes:

- [ ] Have a conviction under federal law, D.C. Code, or Uniform Code of Military Justice
- [ ] Have been released from prison or home/community detention at least five years ago
- [ ] Have been sentenced at least five years ago, if you were not given a prison term
- [ ] Live in the U.S. or its territories

The configurable logic UI must permit the following conditions: 

1. IF the first AND last boxes ARE checked AND the second OR the third box ARE checked, THEN the user should be taken to the first page of the application when they hit "next"
2. IF the first AND last boxes ARE checked AND the second box IS NOT checked AND the third box IS NOT checked, THEN the user should be taken a waiver request page which provides a large text input to describe why they feel they deserve to have the requirement in question waived, after which they will proceed to the first page of the application
3. IF the first AND last box are NOT BOTH checked, THEN the user should proceed to a page explaining that they are not eligible for a presidential pardon and which has no "next" button

We should consider the option to ask up front whether the applicant has received a prison term for the offense in question, as this may simplify the conditional logic and the burden on our form-builder user, but our UI should be to accommodate the scenario above either way.

## Acceptance Criteria

- [ ] Pardon form-builder staff can create the necessary eligibility screen and link it correctly to other screens, in a self-directed way, without instruction beyond what is provided by the UI itself. Ideally, we can validate this with them using a clickable prototype

## Tasks

- [ ] Collab between design and engineering to ensure implementability of designed UI
- [ ] Need to have: static mocks for sufficient Logic UI
- [ ] Nice to have: clickable prototype for sufficient Logic UI

## Definition of done

The "definition of done" ensures our quality standards are met with each bit of user-facing behavior we add. Everything that can be done incrementally should be done incrementally, while the context and details are fresh. If it’s inefficient or “hard” to do so, the team should figure out why and add OPEX/DEVEX backlog items to make it easier and more efficient.

- [ ] Behavior
  - [ ] Acceptance criteria met
  - [ ] Implementation matches design decisions
- [ ] Documentation
  - [ ] ADRs (`/documents/adr` folder)
  - [ ] Relevant `README.md`(s)
- [ ] Code quality
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies; dependency rule followed
  - [ ] Code is reviewed by team member
  - [ ] Code quality checks passed
- [ ] Security and privacy
  - [ ] Automated security and privacy gates passed
- [ ] Testing tasks completed
  - [ ] Automated tests pass
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build and deploy
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted. Document the feature toggle
  - [ ] Source code is merged to the main branch

## Decisions

- *Optional: Any decisions we've made while working on this story*

**Comment by emilylordahl** [comment]
This story relates to learnings from concept testing via #260. Please share with Nichole as she gets deeper into ATJ.

**Comment by emilylordahl** [comment]
@jimmoffet I put this [doc](https://docs.google.com/document/d/1QUFKL1SSn8WjM_oZtvbGFBHVYzD6uHEtIRGNhkWdWQ0/edit) together as guidance/recommendation/resources for Design related to logic. Feel free to share with Nichole! It's in the Design folder within our phase 4 project folder on Drive. Thanks!

**Comment by JennyRichards-Flexion** [comment]
This is related to this [closed issue](https://github.com/GSA-TTS/atj-platform/issues/260).

**Comment by JennyRichards-Flexion** [comment]
This is complete.
