### ISSUE TITLE
Rich text formatting component

### ISSUE THREAD

**Issue by jimmoffet** [GSA-TTS/atj-platform#296]
## Overview

See #257 for more info

> In concept testing, it was discovered that large page titles are typically the first thing people see to orient themselves and that meta information such as form dates, statutes, etc. may require special typographic treatment. In the next phase of designs:
> 
>     Continue to use [USWDS](https://designsystem.digital.gov/components/typography/#source-sans-pro) H1 styling for form page title.
>     Provide flexibility to style text as various USWDS headers while maintaining accessibility best practices for page hierarchy. Meta information such as form dates, statutes, etc. may require special typographic treatment.
> 
> Explore the specific needs when it comes to meta information and design a typographic styling feature that meets said need.
> 
>     Consider that form authors are not UX or product designers, so their knowledge of typographic hierarchy and accessibility is somewhat limited. Markdown is likely unfamiliar to this audience as a styling mechanism. I suggest instead using typographic patterns in tools like Notion or Google Docs (attached examples). Be sure to consider this when designing.

## Context

*Optional: Any reference material or thoughts we may need for later reference, or assumptions of prior or future work that's out of scope for this story.*

- [x] ADR doc to ensure eng team understands implications of tiptap editor integration

## Acceptance Criteria

*Required outcomes of the story*

- [x] Form builder user can edit text using rich text component including, headings, bold, italic, bullets and numbered lists
- [x] Accessibility hierarchy should place user-edited text in appropriate level of the hierarchy of the form edit view 
- [x] Ensure edited text is displayed as expected in the Display/Preview view, including accessibility hierarchy

## Research Questions

- *Optional: Any initial questions for research*

## Tasks

*Research, design, and engineering work needed to complete the story.*

- [x] Tests passing in CI (split to separate ticket?)
- [x] Screenreader QA for changing pages in edit view
- [x] Screenreader QA for changing pages in display view

## Definition of done

The "definition of done" ensures our quality standards are met with each bit of user-facing behavior we add. Everything that can be done incrementally should be done incrementally, while the context and details are fresh. If it’s inefficient or “hard” to do so, the team should figure out why and add OPEX/DEVEX backlog items to make it easier and more efficient.

- [ ] Behavior
  - [ ] Acceptance criteria met
  - [ ] Implementation matches design decisions
- [ ] Documentation
  - [ ] ADRs (`/documents/adr` folder)
  - [ ] Relevant `README.md`(s)
- [ ] Code quality
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies; dependency rule followed
  - [ ] Code is reviewed by team member
  - [x] Code quality checks passed
- [ ] Security and privacy
  - [ ] Automated security and privacy gates passed
- [ ] Testing tasks completed
  - [ ] Automated tests pass
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build and deploy
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted. Document the feature toggle
  - [ ] Source code is merged to the main branch

## Decisions

- *Optional: Any decisions we've made while working on this story*
