### ISSUE TITLE
DEMO - DOJ marijuana pardon application

### ISSUE THREAD

**Issue by danielnaab** [GSA-TTS/atj-platform#77]
https://www.justice.gov/pardon/page/file/1546296/dl?inline
```[tasklist]
### Tasks
- [ ] INGESTION - State fed court vs DC court conditional (how to handle for Friday AND how to handle long term)
- [ ] STRETCH - get page numbers from API implemented
- [ ] INGESTION - get checkboxes parented correctly into fieldset
- [ ] REGRESSION TESTING - Page creation renaming and save
- [ ] REGRESSION - Verify pdf generation works as expected
- [ ] REGRESSION - drag and drop
- [ ] REGRESSION - Urls and routing (including delete form)
- [ ] REGRESSION - Verify all fields are editable and can accept input
```
