### ISSUE TITLE
Kansas name change - design spike

### ISSUE THREAD

**Issue by danielnaab** [GSA-TTS/atj-platform#79]
Explore the Kansas name change process and provide design guidance to team.

Example considerations:

- CRUD for questions after PDF has been uploaded, including inline editing
- Drag and drop to rearrange question order
- CRUD sections
- Lightweight FTUX 
- Accessibility

```[tasklist]
### Tasks (ACs)
- [x] Mocks for small screen support
- [x] Mock-ups, as appropriate, CRUD for questions and sections
- [x] Mocks optimized for larger screens
- [x] Follow-up user stories added to Kansas name change #76: https://github.com/GSA-TTS/atj-platform/issues/76
- [x] Mocks for medium screen support
```

**Comment by emilylordahl** [comment]
Hi all, here is the [mobile section](https://www.figma.com/file/J41m2Ytc3UrzfwJ4CoAkcq/ATJ-Platform?type=design&node-id=678%3A3960&mode=design&t=Tapf4M5Qh0FF2XOd-1) of the design mocks in Figma that have been broken down into tasks for implementation. @danielnaab @natashapl @jasnakai @jimmoffet  cc @espythomson

**Comment by emilylordahl** [comment]
Please note that we've migrated to a new GSA Figma space. Design work is now tracked in Figma [here](https://www.figma.com/file/RAm1GWbVTdBpzlmaLL6pLO/ATJ-Platform?type=design&node-id=574%3A170&mode=design&t=QCuKM2vtr0mxZT7e-1).
