### ISSUE TITLE
Implement form builder design

### ISSUE THREAD

**Issue by danielnaab** [GSA-TTS/atj-platform#97]
Implement the designs produced by #79.

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/atj-platform/issues/98
- [ ] https://github.com/GSA-TTS/atj-platform/issues/99
- [ ] https://github.com/GSA-TTS/atj-platform/issues/100
- [ ] https://github.com/GSA-TTS/atj-platform/issues/101
- [ ] https://github.com/GSA-TTS/atj-platform/issues/102
- [ ] https://github.com/GSA-TTS/atj-platform/issues/103
- [ ] https://github.com/GSA-TTS/atj-platform/issues/104
- [ ] https://github.com/GSA-TTS/atj-platform/issues/105
```
